app/forms.py
from wtforms import Form
from wtforms import validators
from wtforms import StringField, PasswordField, IntegerField


class LoginForm(Form):
    username = StringField(u'Username', [
    validators.Required(), validators.length(min=4, max=20, message='El username no cumple con los requisitos')
    ])
    password = PasswordField(u'Password', [
    validators.Required(), validators.length(min=8, max=15, message='Contraseña no valida')
    ])
    age = IntegerField(u'Age', [validators.Required(message='Por favor llena este campo')])

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_wtf.csrf import CSRFProtect
from flask_mysqldb import MySQL
from flask import render_template, request

bootstrap = Bootstrap()
csrf = CSRFProtect()
app = Flask(__name__)
db = MySQL(app)

from .views import page

def create_app(config):

    csrf.init_app(app)
    app.config.from_object(config)
    bootstrap.init_app(app)
    app.register_blueprint(page)
    return app



@page.route('/libros')
def listar_libros():
    try:
        cursor= db.connection.cursor()
        sql='SELECT isbn, titulo, anoedicion FROM libro ORDER BY titulo ASC'
        cursor.execute(sql)
        data=cursor.fetchall()
        data = {
            'libros':data
        }
        #return 'Ok. Número de libros = {0}'.format(len(data))
        return render_template('libros.html', data=data, title='libros')
    except Exception as ex:
        raise Exception(ex)

app/views.py
from flask import Blueprint
from flask import render_template, request
from .forms import LoginForm

page = Blueprint('page', __name__)


@page.app_errorhandler(404)
def not_founded(error):
       return render_template('errors/404.html', title='ERROR'), 404

@page.route('/productos')
def productos():
    return render_template('productos.html', title='Products')

@page.route('/')
def index():
    return render_template('index.html', title = 'Home')

@page.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)

    if request.method == 'POST' and form.validate():
        print(form.username.data)
        print(form.password.data)
        print(form.age.data)
        print('Nueva sesion creada')
    return render_template('auth/login.html', title='Login', form=form)

@page.route('/historia')
def hist():
    return render_template('historia.html', title='Historia')

@page.route('/log')
def log():
    return render_template('auth/log.html', title='Log')

app/templates/helpers/_form.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

app/templates/historia.html
{% extends 'layout.html' %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/nav.css')}}">
{% endblock %}

{% block container %}
<div class="col-md-8 offset-md-2">
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="w-75 p-3"w-75 p-3 src="{{url_for('static', filename='images/3.jpg')}}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{{url_for('static', filename='images/3.jpg')}}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{{url_for('static', filename='images/3.jpg')}}"  alt="Third slide">
      <div class="carousel-caption d-none d-md-block">
    <h5>100 años de libertad</h5>
    <p>Garbiel Garcia Marquez, editorial sol, best seller</p>
  </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'lay.html' %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}
{% block content %}
<div class="row">
<div class="col-md-10 offset-md-1">
<div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="first-slide" src="{{url_for('static', filename='images/4.jpg')}}" alt="First slide">
            <div class="container">
              <div class="carousel-caption text-left">
                <h1>Example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="second-slide" src="{{url_for('static', filename='images/2.jpg')}}"  alt="Second slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Another example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="third-slide" src="{{url_for('static', filename='images/1.jpg')}}"  alt="Third slide">
            <div class="container">
              <div class="carousel-caption text-right">
                <h1>One more for good measure.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
</div>
</div>

      <div class="container marketing">

              <!-- Three columns of text below the carousel -->
              <div class="row">
                <div class="col-lg-4">
                  <img class="rounded-circle" src="{{url_for('static', filename='images/3.jpg')}}" alt="Generic placeholder image" width="140" height="140">
                  <h2>Vida</h2>
                  <p>Un pequeño fragmento de mi vida, historia, origenes, visión.</p>
                  <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
                </div><!-- /.col-lg-4 -->
                <div class="col-lg-4">
                  <img class="rounded-circle" src="{{url_for('static', filename='images/3.jpg')}}" alt="Generic placeholder image" width="140" height="140">
                  <h2>Estudios</h2>
                  <p>Mi recorrido académico, dastante mediocre, pero se ha logrado avanzar hasta este punto</p>
                  <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
                </div><!-- /.col-lg-4 -->
                <div class="col-lg-4">
                  <img class="rounded-circle" src="{{url_for('static', filename='images/3.jpg')}}" alt="Generic placeholder image" width="140" height="140">
                  <h2>Interes</h2>
                  <p>Mis hobbies, distracciones, intereses en general.</p>
                  <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
                </div><!-- /.col-lg-4 -->
              </div><!-- /.row -->
{% endblock %}

app/templates/lay.html
{% extends 'bootstrap/base.html' %}


{% block tittle %}
  {{ title }}
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    </button>
    <a class="navbar-brand" href="{{url_for('page.index')}}"><img src="{{url_for('static', filename='images/3.jpg')}}" alt="" width="50" height="60">PORRO</a>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('page.index') }}">index</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link"href="{{url_for('page.productos') }}">Products</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('page.login')}}">Login</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#"  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Otros</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{url_for('page.hist')}}">Hisoria</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
      </div>
        </li>
      </ul>
    </div>
    </div>
</nav>
</nav>
{% endblock %}

{% block content %}
{% endblock %}

app/templates/layout.html
{% extends 'bootstrap/base.html' %}


{% block tittle %}
  {{ title }}
{% endblock %}

{% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
    <div class="container">
      <a class="navbar-brand" href="{{url_for('page.index')}}"><img src="{{url_for('static', filename='images/3.jpg')}}" alt="" width="50" height="60">PORRO</a>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{url_for('page.index') }}">index</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link"href="{{url_for('page.productos') }}">Products</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{url_for('page.login')}}">Login</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#"  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Otros</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}


{% block content %}
<div class="container-fluid">
  <div class="row">
    {% block container %}
    {% endblock %}
  </div>
</div>
{% endblock %}

app/templates/libros.html
{% extends 'lay.html' %}

{% block content %}
<table>
  {% for l in data.libros %}
    <tr>
      <td>{{ l[0] }}</td>
      <td>{{ l[1] }}</td>
      <td>{{ l[2] }}</td>
    </tr>
  {% endfor %}
</table>
{% endblock %}

app/templates/productos.html
{% extends 'lay.html' %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/prod.css')}}">
{% endblock %}

{% block content %}
<div class="container-fluid">
<div class="row">
<div class="col-sm-6 col-md-6 col-lg-6 col-xl-6" class="Español"><center>Español</center></div>
<div class="col-sm-6 col-md-6 col-lg-6 col-xl-6"><center>English</center></div>
<div class="col-sm-6 col-md-6 col-lg-6 col-xl-6"><center>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc lacinia tristique vulputate. Aenean mollis at augue eget aliquam. Suspendisse vestibulum hendrerit odio non tristique. Vestibulum et ipsum elit. Sed quis mauris lacus. Sed elementum nisi nisl, et fringilla massa ultricies id. Aliquam malesuada at ligula a sollicitudin. Donec sollicitudin lectus vitae bibendum vehicula. Phasellus nec auctor purus, vel auctor diam. Duis tempor sem sodales laoreet elementum. Nullam et pellentesque risus. Cras sollicitudin ipsum et interdum suscipit. Proin rutrum, lacus posuere faucibus egestas, augue quam condimentum risus, id venenatis ipsum elit non ex.</center></div>
<div class="col-sm-6 col-md-6 col-lg-6 col-xl-6"><center>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc lacinia tristique vulputate. Aenean mollis at augue eget aliquam. Suspendisse vestibulum hendrerit odio non tristique. Vestibulum et ipsum elit. Sed quis mauris lacus. Sed elementum nisi nisl, et fringilla massa ultricies id. Aliquam malesuada at ligula a sollicitudin. Donec sollicitudin lectus vitae bibendum vehicula. Phasellus nec auctor purus, vel auctor diam. Duis tempor sem sodales laoreet elementum. Nullam et pellentesque risus. Cras sollicitudin ipsum et interdum suscipit. Proin rutrum, lacus posuere faucibus egestas, augue quam condimentum risus, id venenatis ipsum elit non ex.</center></div>
</div>
<div class="row">
<div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
  <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{url_for('static', filename='images/3.jpg')}}" alt="Card image cap">
  <h1 class="card-title">Libros</h1>
  <div class="card-header">
    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseUno" aria-expanded="false" aria-controls="collapseOne">
          Ver más...
    </button>
    <div id="collapseUno" class="collapse" aria-labelledby="headingOne">
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
  </div>
  </div>
</div>
</div>
<div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
  <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{url_for('static', filename='images/3.jpg')}}" alt="Card image cap">
  <h1 class="card-title">Novelas Ligeras</h1>
  <div class="card-header">
    <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Ver más...
        </button>
  </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
        <div class="card-body">
          Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
        </div>
      </div>
  </div>
  </div>
  <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
    <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="{{url_for('static', filename='images/3.jpg')}}" alt="Card image cap">
    <h1 class="card-title">Juegos</h1>
    <div class="card-header">
      <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseTwo">
            Ver más...
          </button>
    </div>
          <div id="collapseThree" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
          <div class="card-body">
            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
          </div>
        </div>
    </div>
    </div>
</div>
</div>
{% endblock %}

app/templates/vert.html
{% extends 'bootstrap/base.html' %}


{% block tittle %}
  {{ title }}
{% endblock %}

{% block navbar %}
<nav id="navbar-example3" class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <nav class="nav nav-pills flex-column">
    <a class="nav-link" href="#item-1">Item 1</a>
    <nav class="nav nav-pills flex-column">
      <a class="nav-link ml-3 my-1" href="#item-1-1">Item 1-1</a>
      <a class="nav-link ml-3 my-1" href="#item-1-2">Item 1-2</a>
    </nav>
    <a class="nav-link" href="#item-2">Item2</a>
    <a class="nav-link" href="#item-3">Item3</a>
    <nav class="nav nav-pills flex-column">
      <a class="nav-link ml-3 my-1" href="#item-3-1">Item 3-1</a>
      <a class="nav-link ml-3 my-1" href="#item-3-2">Item 3-2</a>
    </nav>
  </nav>
</nav>
{% endblock %}

{% block content %}
{% endblock %}